name: ecoschedule
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.7.0
  path_provider: ^1.6.10
  sembast: ^2.4.4+3
  equatable: ^1.2.0
  dropdown_formfield: ^0.1.2
  flutter_svg: 0.17.4
  flutter_spinkit: 4.1.2+1
  flutter_typeahead: ^1.8.1
  recase: ^3.0.0
  intl: ^0.16.1
  collection: ^1.14.12
  auto_size_text: ^2.1.0
  http: ^0.12.1
  font_awesome_flutter: ^8.8.1
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  sticky_headers: 0.1.8+1
  google_fonts: 1.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

# dev_dependencies:
# flutter_test:
#   sdk: flutter

flutter:
  uses-material-design: true
